export const SEED_CONFESSIONS = [
  {
    id: "seed-1",
    text: "My PPA is a primary school with no chairs. I teach 60 kids standing up every day. I am a graduate of Mechanical Engineering.",
    tag: "PPA Wahala",
    batch: "2025B",
    reactions_cry: 412,
    reactions_laugh: 289,
    reactions_dead: 178,
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    is_approved: true,
  },
  {
    id: "seed-2",
    text: "My LGI demanded ₦10,000 from everyone or she won't sign our files. I paid. God is watching her.",
    tag: "LGI Nonsense",
    batch: "2025A",
    reactions_cry: 891,
    reactions_laugh: 123,
    reactions_dead: 445,
    created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
    is_approved: true,
  },
  {
    id: "seed-3",
    text: "I have been at my PPA for 3 months. Nobody knows my name. I sign in, sit down, sign out. I think I'm a ghost.",
    tag: "Ghost Corper",
    batch: "2025B",
    reactions_cry: 234,
    reactions_laugh: 678,
    reactions_dead: 312,
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    is_approved: true,
  },
  {
    id: "seed-4",
    text: "The mammy market man charged me ₦800 for indomie because I was wearing khaki. Removed the khaki. He charged me ₦450. Same pot. Same fire.",
    tag: "Khaki Tax",
    batch: "2024C",
    reactions_cry: 156,
    reactions_laugh: 1203,
    reactions_dead: 567,
    created_at: new Date(Date.now() - 6 * 3600000).toISOString(),
    is_approved: true,
  },
  {
    id: "seed-5",
    text: "My allowee finished on the 7th day. I still have 24 days left. Please pray for me. I am not strong.",
    tag: "Allowee Crisis",
    batch: "2025A",
    reactions_cry: 789,
    reactions_laugh: 345,
    reactions_dead: 234,
    created_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    is_approved: true,
  },
  {
    id: "seed-6",
    text: "Got posted to Kebbi. Googled Kebbi. Cried. Packed my bags. Remembered redeployment costs money. Unpacked. Cried again.",
    tag: "Redeployment Dreams",
    batch: "2025B",
    reactions_cry: 567,
    reactions_laugh: 890,
    reactions_dead: 423,
    created_at: new Date(Date.now() - 10 * 3600000).toISOString(),
    is_approved: true,
  },
  {
    id: "seed-7",
    text: "The Man O' War instructor said my marching is an insult to the Nigerian army. I am a UK returnee. I did not come here for this.",
    tag: "Camp Suffering",
    batch: "2024C",
    reactions_cry: 345,
    reactions_laugh: 1456,
    reactions_dead: 678,
    created_at: new Date(Date.now() - 12 * 3600000).toISOString(),
    is_approved: true,
  },
  {
    id: "seed-8",
    text: "My CDS group is 47 people. We do community development every Thursday by sitting under a mango tree and discussing why Nigeria is hard.",
    tag: "CDS Wahala",
    batch: "2025A",
    reactions_cry: 123,
    reactions_laugh: 987,
    reactions_dead: 456,
    created_at: new Date(Date.now() - 24 * 3600000).toISOString(),
    is_approved: true,
  },
  {
    id: "seed-9",
    text: "Woke up at 4am for parade. Stood in the rain for 2 hours. Camp coordinator announced activities cancelled due to rain. I have lost faith in everything.",
    tag: "Camp Suffering",
    batch: "2025B",
    reactions_cry: 678,
    reactions_laugh: 567,
    reactions_dead: 389,
    created_at: new Date(Date.now() - 26 * 3600000).toISOString(),
    is_approved: true,
  },
  {
    id: "seed-10",
    text: "My principal at PPA asks me to resume by 7am. I arrive 7:05. She is never there before 9:30. I have documented this 43 times.",
    tag: "PPA Wahala",
    batch: "2024C",
    reactions_cry: 234,
    reactions_laugh: 1123,
    reactions_dead: 567,
    created_at: new Date(Date.now() - 28 * 3600000).toISOString(),
    is_approved: true,
  },
  {
    id: "seed-11",
    text: "The hostel toilet situation in camp... I have decided I don't need to use the bathroom anymore. I will hold it for 21 days. This is my plan.",
    tag: "Camp Suffering",
    batch: "2025A",
    reactions_cry: 890,
    reactions_laugh: 456,
    reactions_dead: 712,
    created_at: new Date(Date.now() - 36 * 3600000).toISOString(),
    is_approved: true,
  },
  {
    id: "seed-12",
    text: "Someone stole my white shoe from camp hostel. Wore a black one and a white one to parade. Military man screamed at me for 20 minutes. I understand.",
    tag: "Camp Suffering",
    batch: "2025B",
    reactions_cry: 345,
    reactions_laugh: 2103,
    reactions_dead: 890,
    created_at: new Date(Date.now() - 48 * 3600000).toISOString(),
    is_approved: true,
  },
]

export const TAGS = [
  "All",
  "PPA Wahala",
  "LGI Nonsense",
  "Ghost Corper",
  "Khaki Tax",
  "Allowee Crisis",
  "Redeployment Dreams",
  "Camp Suffering",
  "CDS Wahala",
]

export const TAG_COLORS: Record<string, string> = {
  "PPA Wahala": "#FF6B35",
  "LGI Nonsense": "#E63946",
  "Ghost Corper": "#9B72CF",
  "Khaki Tax": "#2EC4B6",
  "Allowee Crisis": "#E9C46A",
  "Redeployment Dreams": "#F4A261",
  "Camp Suffering": "#52B788",
  "CDS Wahala": "#74C0FC",
}
